---
# tasks file for Configure NGINX

- name: Install NGINGX
  apt:
    name: nginx
    update_cache: true 

- name: Template nginx.conf
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  register: nginx_info 

- name: Restart NGINX 
  service: 
    name: nginx
    state: restarted 

  